---
- name: Check if OpenVPN config exists
  stat:
    path: /etc/openvpn/client/test.ovpn
  register: file_status

- name: Delete the file if it exists
  ansible.builtin.file:
    path: /etc/openvpn/client/test.ovpn
    state: absent
  when: file_status.stat.exists
  register: previous_vpn_config_delete_log

- name: Copy .ovpn file to remote server log
  ansible.builtin.debug:
    var: previous_vpn_config_delete_log

- name: Copy .ovpn file to remote server
  ansible.builtin.copy:
    src: "{{ ovpn_file }}"
    dest: /etc/openvpn/client/test.conf
    owner: root
    group: root
    mode: '0644'
  register: copy_file_log

- name: Copy .ovpn file to remote server log
  ansible.builtin.debug:
    var: copy_file_log

- name: Start the openvpn service
  ansible.builtin.systemd_service:
    name: openvpn-client@test
    state: started
  register: openvpn_start_log

- name: Start the openvpn service log
  ansible.builtin.debug:
    var: openvpn_start_log

- name: Configure resolvectl for tun0
  ansible.builtin.command: "{{ item }}"
  become: yes
  loop:
    - resolvectl dns tun0 8.8.8.8
    - resolvectl domain tun0 ~
  register: configure_resolvectl_for_tun0_log

- name: Configure resolvectl for tun0 log
  ansible.builtin.debug:
    var: configure_resolvectl_for_tun0_log

- name: Restart systemd resolved service
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
