---
- name: Push to private registry
  community.docker.docker_image:
    name: "{{ dest_registry }}/{{ dest_image_name }}:{{ dest_image_tag }}"
    push: true
    source: local
  register: push_log

- name: Push log
  ansible.builtin.debug:
    msg: '{{ push_log }}'
