---
- name: Get latest Harbor release info from GitHub
  ansible.builtin.uri:
    url: https://api.github.com/repos/goharbor/harbor/releases/latest
    return_content: yes
  register: harbor_release_info

- name: Set Harbor version variable
  ansible.builtin.set_fact:
    harbor_version: "{{ harbor_release_info.json.tag_name }}"

- name: Download latest Harbor offline installer
  ansible.builtin.get_url:
    url: "https://github.com/goharbor/harbor/releases/download/{{ harbor_version }}/harbor-online-installer-{{ harbor_version }}.tgz"
    dest: "/tmp/harbor-online-installer-{{ harbor_version }}.tgz"
    timeout: 600
  register: harbor_online_installer_download_log

- name: Download latest Harbor online installer log
  ansible.builtin.debug:
    var: harbor_online_installer_download_log

- name: Extract archive
  ansible.builtin.unarchive:
    src: "/tmp/harbor-online-installer-{{ harbor_version }}.tgz"
    dest: "/tmp"
    remote_src: yes
  register: extract_harbor_log

- name: Extract archive log
  ansible.builtin.debug:
    var: extract_harbor_log

- name: Copy and rename harbor.yml
  ansible.builtin.copy:
    remote_src: yes
    src: "/tmp/harbor/harbor.yml.tmpl"
    dest: "/tmp/harbor/harbor.yml"

- name: Update hostname in harbor.yml
  ansible.builtin.lineinfile:
    path: /tmp/harbor/harbor.yml
    regexp: '^hostname:\s*reg\.mydomain\.com\s*$'
    line: 'hostname: {{ harbor_hostname }}'
    backup: yes

- name: Comment out https section in harbor.yml
  ansible.builtin.replace:
    path: /tmp/harbor/harbor.yml
    regexp: '^(https:|  port: 443|  certificate: .+|  private_key: .+)$'
    replace: '# \1'

- name: Run harbor install script
  become: true
  shell: /tmp/harbor/install.sh
  args:
    executable: /bin/bash
  register: harbor_install_script_log

- name: Harbor install script log
  ansible.builtin.debug:
    var: harbor_install_script_log
