- name: Create docker container
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: "{{ container_image }}"
    state: "{{ container_state }}"
    restart_policy: "{{ container_restart_policy }}"
    network_mode: "{{ container_network_mode }}"
    working_dir: "{{ container_workdir }}"
    cpu_period: "{{ container_cpu_period }}"
    cpu_quota: "{{ container_cpu_quota }}"
    memory: "{{ container_memory }}"
    detach: "{{ container_detach }}"
    exposed_ports:
      - "{{ container_exposed_ports | map('split', ':') | map(attribute=0) | list }}"
    published_ports: "{{ container_published_ports }}"
    env: "{{ container_envs }}"
    volumes: "{{ container_volumes }}"
  when: container_state == "present"
  register: container_creation_log

- name: Container creation log
  ansible.builtin.debug:
    msg: "{{ container_creation_log }}"
