---
- name: Pull image in remote server and push it to private registry
  hosts: docker_hosts
  become: true
  roles:
    - role: docker_image_pull
      vars:
        docker_image_name: "{{ source_image_full }}"
        docker_image_tag: "{{ source_image_tag }}"

    - role: docker_image_tag
      vars:
        source_image_full: ""
        source_image_tag: ""
        dest_registry: ""
        dest_image_name: ""
        dest_image_tag: ""

    - role: docker_image_push
      vars:
        dest_registry: ""
        dest_image_name: ""
        dest_image_tag: ""

    - role: docker_image_delete
      vars:
        docker_image_name: "{{ dest_registry }}/{{ dest_image_name }}"
        docker_image_tag: "{{ dest_image_tag }}"

    - role: docker_image_delete
      vars:
        docker_image_name: "{{ source_image_full }}"
        docker_image_tag: "{{ source_image_tag }}"
      when: image_exists == '0'
