---
- name: Replace the default proxy entry with your own
  ansible.builtin.lineinfile:
    path: /etc/proxychains.conf
    regexp: '^socks4\s+(?:\d{1,3}\.){3}\d{1,3}\s+\d{1,5}$'
    line: "{{ proxy_server }}"
    owner: root
    group: root
    mode: '0644'
  register: proxychain_configuration_log
  become: true

- name: Proxychain configuration log
  ansible.builtin.debug:
    var: proxychain_configuration_log
